### ISSUE TITLE
Key Error When Using Tutorials

### ISSUE THREAD

**Issue by EOrput** [epi2me-labs/labslauncher#12]
Hello, I'm not sure if this is the correct place to post this, but I am having a code issue with EPI2ME Labs. On Friday, I was working through the isoform tutorial and everything was running smoothly, however when I tried to continue using it today after updating to the latest version, I keep getting the error shown below when I try to load in the files. I'm unsure if this has anything to do with the new release or if I've just messed up the notebook somehow, but it seems to be occurring with other tutorial notebooks as well, not just the isoform tutorial one. The only thing I've done differently since Friday that I can think of is update to the latest release. I have very little experience with coding or debugging so I am confused as to how I might go about fixing the problem Any assistance on this matter would be much appreciate, and again I apologize if this is not the correct place to post about this issue.

KeyError                                  Traceback (most recent call last)
/opt/conda/lib/python3.8/site-packages/ipywidgets/widgets/widget_output.py in __enter__(self)
    110         ip = get_ipython()
    111         if ip and hasattr(ip, 'kernel') and hasattr(ip.kernel, '_parent_header'):
--> 112             self.msg_id = ip.kernel._parent_header['header']['msg_id']
    113             self.__counter += 1
    114 

KeyError: 'header'

**Comment by EOrput** [comment]
Sounds good. Thanks for looking into it!

**Comment by Karhide** [comment]
Hi @EOrput 

Would you mind trying again? Labs launcher should prompt an update of the docker image we are using, which hopefully contains a fix. If that doesn't work, please let us know!

Sorry for the inconvenience

**Comment by EOrput** [comment]
Hello,

Everything appears to be working as intended now. Thanks so much!
