### ISSUE TITLE
Ports not available error

### ISSUE THREAD

**Issue by amblina** [epi2me-labs/labslauncher#14]
Created on behalf of @st-pfister!
------------
Hey there,
thanks for opening this conversation! I am a complete bioinformatics beginner and am trying to get EPI2ME Labs notebook server working on my Mac via the EPI2MELabs Launcher and Docker, but I cannot start a server successfully. In Docker, I am getting a server error message (HTTP code 500) that my "ports are not available" and that also the "bind: address is already in use". In EPI2MELabs, it just says that the server is created, but last attempt to start failed. I did not change any of the three. pre-set options for server/token/port yet. And suggestions what I am doing wrong?

Thanks in advance!

**Comment by amblina** [comment]
Hi @st-pfister,
Thanks for trying out epi2me labs notebooks - we're always eager to hear from beginners such as yourself so we can improve our service! I'm sorry to hear this isn't working for you so far. Can I check whether you have run an jupyter notebook before on this mac?  Could you include a screenshot of the launcher when you try and run the launcher plus any error messages you are getting so we can help solve your issue. Thanks!
Amber

**Comment by st-pfister** [comment]
hey @amblina thanks a lot! 
So far I have used JupyterLab to get familiar with _conda_ via the Anaconda-Navigator. (I followed https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html#managing-envs).

Here are  the screenshots of the errors from EPI2ME Launcher and Docker.

<img width="396" alt="Screenshot 2021-06-02 at 16 29 28" src="https://user-images.githubusercontent.com/62891990/120499589-7cced900-c3c0-11eb-86b5-39728074292b.png">
<img width="391" alt="Screenshot 2021-06-02 at 16 30 34" src="https://user-images.githubusercontent.com/62891990/120499598-7e000600-c3c0-11eb-82f0-f2efe250a889.png">
<img width="1243" alt="Screenshot 2021-06-02 at 16 31 23" src="https://user-images.githubusercontent.com/62891990/120499603-7e989c80-c3c0-11eb-990e-92e9d483c027.png">

**Comment by st-pfister** [comment]
hey there, so do you know, what my issue is? 
or have an idea, what I could try?
Thanks;
Stefan

**Comment by amblina** [comment]
Hi @st-pfister ,
Sorry I missed this message!! The error message you are seeing suggests that you already have something running using this port so the best bet is to first find a port which is definitely free:

Try running this command in terminal:

`lsof -i -P -n | grep LISTEN`

This will list a series of ports that are currently being used - if you select a number not on the list (check the last column!) you should be good to go.  It is possible that you have a container already running on that machine port.  To check this try running the following command:

`docker ps`

This will list the containers that are currently running - I'm currently running Epi2me-Labs Server so the list contains the following:

![image](https://user-images.githubusercontent.com/999897/123323610-a85f6200-d52d-11eb-8be5-c2c4a2880a33.png)

The `PORTS` column displays what ports are being used by this active container.

We are working on a feature in the future which will make the task of selecting an appropriate port easier!

Thank you for your patience,
Amber

**Comment by st-pfister** [comment]
Hey Amber, 
thank you so much, I indeed had this port running already and now was able to get EPI2MELabs started on other ports (I just took the neighbouring port numbers, I hope this won't cause any issues).
Thank you again! 
Stefan

**Comment by amblina** [comment]
No worries at all! And choosing a different port should not cause any issues with running the app :)
