### ISSUE TITLE
Qt plugin error with lablauncher on server side

### ISSUE THREAD

**Issue by callumparr** [epi2me-labs/labslauncher#17]
I have tried starting labslauncher on server and use localhost to run through jupyterlabs. 

I can get this to work on a linux box I have in the lab and the sys.admin installed epi2melagbs on the nodes that has plenty of 16 CPU and 2 GPUs and also running rootless-docker , using systemctl --user start docker.service. 

I ssh'd to the server side both with and without the DISPLAY variable 

`DISPLAY=:0 ssh -Y -L 8888:localhost:8888 -L 8889:localhost:8889 callum@xxxx`

```
callum@xxxx:~$ labslauncher 
Invalid MIT-MAGIC-COOKIE-1 keyqt.qpa.xcb: could not connect to display localhost:10.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

/usr/local/bin/labslauncher: line 3: 4031651 Aborted                 (core dumped) /usr/local/bin/EPI2ME-Labs-Launcher/EPI2ME-Labs-Launcher $@
```

`ssh -X -L 8888:localhost:8888 -L 8889:localhost:8889 callum@xxxx`

```
(base) callum@xxxx:~$ labslauncher 
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

/usr/local/bin/labslauncher: line 3: 4042008 Aborted                 (core dumped) /usr/local/bin/EPI2ME-Labs-Launcher/EPI2ME-Labs-Launcher $@
```

**Comment by amblina** [comment]
Hi @callumparr 
Can you try on your host machine running the following command:

`xeyes`

This is fun little program which pops a set of googley eyes that follow your cursor around. If this works fine, please try again to run the ssh command as before e.g.

`DISPLAY=:0 ssh -Y -L 8888:localhost:8888 -L 8889:localhost:8889 callum@xxxx`

Then rather than starting labslauncher, can you try and run `xeyes` again in the same way and see if this works. If it does - please try and run the launcher again if not let me know what error messages you come across. Hopefully we can get to the bottom of this together!

Amber

**Comment by callumparr** [comment]
I can run `xeyes` on my host system macOS and ubuntu 18.04.

If login with `DISPLAY=:0 ssh -Y -L 8888:localhost:8888 -L 8889:localhost:8889 callum@xxxx`

I get following error:

`Invalid MIT-MAGIC-COOKIE-1 keyError: Can't open display: localhost:10.0`

For:
`DISPLAY=:0 ssh -X -L 8888:localhost:8888 -L 8889:localhost:8889 callum@xxxx`

```
(base) callum@dgt-gpu2:~$ xeyes
Error: Can't open display:
```

If I run with out DISPLAY variable and using -Y and not -X:

`ssh -Y -L 8888:localhost:8888 -L 8889:localhost:8889 callum@xxx `

I can get the `xeyes` graphical output.

I can then get the` labslauncher` window to appear in my Xqartz window. But if I start the container I then get the issue I have raised elsewhere:

https://github.com/epi2me-labs/labslauncher/issues/18#issue-926941812

**Comment by amblina** [comment]
I'm glad to hear that the labslauncher is now rendering for you - I'll continue to support you on your other issue threads!

**Comment by callumparr** [comment]
@amblina TY. Yes, I suspect the other issue is that we are running rootless-docker but I am seeing in the first steps of install lablauncher we have to add `sudo usermod -aG docker <username>`. As this is running on our division's cluster I cannot do this. But we use `systemtctl --user start docker` so we can run docker without sudo so same effect?
