### ISSUE TITLE
installation of guppy_basecaller crashed the labslauncher

### ISSUE THREAD

**Issue by spanferkelfan** [epi2me-labs/labslauncher#19]
Hi!
We installed Epi2meLabs on our workstation and it worked fine. A few days later we installed the guppy_basecaller, now we can't start the labslauncher anymore. Did we overwrite some settings? Is there a way to have back the labslauncher without re-installing everything? It's not possible to post the log file of the labslauncher since the application seems to be completely deleted. I can only see the labsmanager. We are using a workstation running Ubuntu 18.04.5
Cheers,
spanferkelfan

**Comment by amblina** [comment]
Hi @spanferkelfan! Could you confirm if you have tried to reinstall labslauncher and if you have, how have you been installing it? If you do give it a go can you show me how you are running it and what happens after installing.  Are you having issues running labsmanager as well or is it just labslauncher you are having issues with?
Thanks!
Amber
