### ISSUE TITLE
epi2me-labs-launcher crash on launch when docker desktop is already open (macOS)

### ISSUE THREAD

**Issue by GianlucaDamaggio** [epi2me-labs/labslauncher#2]
This morning I have launched and used epi2me-labs (v0.4.2) smoothly but after the docker notebook v0.1.1 upgrade the launcher not work and continues to crash at launch when docker desktop is open. 
I have the latest version for docker desktop (2.3.0.3, stable) and the latest version of macOS Catalina (10.15.5)

**Comment by cjw85** [comment]
Thanks for reporting this. A patch was made to the server to fix an issue with some notebooks, which had a knock on consequence for the launcher. I have applied remedial action that should allow the launcher to work again. A permanent fix for this is due to be released shortly.

**Comment by GianlucaDamaggio** [comment]
Now it works perfectly, thanks for your help.
Great regards

**Comment by cjw85** [comment]
No problem.
