### ISSUE TITLE
> Hi Amber,

### ISSUE THREAD

**Issue by cjw85** [epi2me-labs/labslauncher#20]
> Hi Amber,
> 
> I attached screen shots here.
> 
> ![1](https://user-images.githubusercontent.com/65312235/120035472-46f6b280-bfc4-11eb-8c50-b5ce65126e6a.png)
> 
> ![2](https://user-images.githubusercontent.com/65312235/120035519-5d047300-bfc4-11eb-9ba0-0812e0829010.png)
> 
> ![3](https://user-images.githubusercontent.com/65312235/120035527-5f66cd00-bfc4-11eb-9269-262a904a7214.png)
> 
> ![4](https://user-images.githubusercontent.com/65312235/120035529-6097fa00-bfc4-11eb-8e79-33887e84e385.png)

Hi! I have these exact same issues on Ubuntu, how can I fix this?

_Originally posted by @mmnascimento in https://github.com/epi2me-labs/labslauncher/issues/13#issuecomment-923169583_

**Comment by cjw85** [comment]
Hi @mmnascimento,

I suspect this is due to a lack of permissions for running docker. I can see from your Ubuntu screenshot that you have run

```sudo docker run helloworld```

The command has run correctly with elevated priveleges, however when you are running the labslaucnher program it will not be running with such priveleges and hence it cannot communicate with docker. You will need to add your user account to the docker group as noted in quick start guide: https://labs.epi2me.io/nbquickstart/

**Comment by mmnascimento** [comment]
Hi  @cjw85 , 

Problem solved!

**Comment by callumparr** [comment]
Is there anyway around this issue. Our sys admin installed labslauncher on one of our nodes that has rooltless-docker running and added various users. 

I start docker service 

ssh login 
`systemctl --user start docker.service `

However if I try to start the epi2melabs either with labslauncher with Qt widget or the labsmanager there seem to be a permissions issue. 

I asked if they can add my user to the docker user groups but I am sure if that relates in our use case on the node.

**Comment by cjw85** [comment]
I'm sorry I have no experience of using rootless docker. Your best bet is to talk to your sys admin people. labslauncher is doesn't try to do anything terribly sophisticated, its just a UI to help users start the JupyterLab container in a consistent manner without requiring using the command-line.

**Comment by callumparr** [comment]
> I'm sorry I have no experience of using rootless docker. Your best bet is to talk to your sys admin people. labslauncher is doesn't try to do anything terribly sophisticated, its just a UI to help users start the JupyterLab container in a consistent manner without requiring using the command-line.

Thank you. Yes, so it's a permissions issue. The sys.admin confirmed adding his user to the docker user group he can run the labslauncher and labs manager. 

Going forward I think I can use the nextflow workflows for my actual data using the conda method instead of the standard docker containerization.

**Comment by MarwaElnaiem** [comment]
> Hi @cjw85 ,
> 
> Problem solved!
Would you please outline how did you solve the problem?
thanks

**Comment by callumparr** [comment]
It was resolved in that it was a permissions issue. If you are permitted on your system, you need to add your user to docker group which the tutorial for quickstart documents after installing docker.
