### ISSUE TITLE
Fresh VM, labslauncher fails

### ISSUE THREAD

**Issue by genignored** [epi2me-labs/labslauncher#21]
Hi,

I am nearly certain this is a dependency issue, but I need help figuring out what libraries are missing to enable us to perform an install.

As background, this is a VM that was spun up, so it has minimal packages installed.  I am currently getting an error during the 
``` PYTHON=python3 make run ```
step, which is giving this:

``` 
Using /data/lrn/conda/envs/EPI2MELabs/labslauncher/venv/lib/python3.9/site-packages/wrapt-1.13.0rc3-py3.9-linux-x86_64.egg
Finished processing dependencies for labslauncher==1.2.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```

Using CentOS7 as the base.

Thank you,
=matt scholz

**Comment by cjw85** [comment]
Hi Matt,

The [release page](https://github.com/epi2me-labs/labslauncher/releases/tag/v1.2.0) contains an RPM package suitable for CentOS 7. This should ease your pains.

**Comment by genignored** [comment]
You can resolve this now.  it was an SSL-certificate issue.
