### ISSUE TITLE
cannot install pychopper via conda in epi2melabs 

### ISSUE THREAD

**Issue by callumparr** [epi2me-labs/labslauncher#3]
Installed epi2melabs on ubuntu and connect to my local run time to run cDNA tutorial with my own data. 

The first code snippet to install pychopper fails. I had previously run a couple of tutorials with sample data and it worked OK. After an update it seems something wrong with conda environment. 

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are missing from the target environment:
  - protobuf==3.12
```

**Comment by cjw85** [comment]
@callumparr 

Thanks for reporting this, I'm taking a look now.

**Comment by cjw85** [comment]
I can confirm I can reproduce this.

Changing `!conda install` to `mamba install` appears to work (I don't know why this would be). I will update the notebook on github.
