### ISSUE TITLE
Errors with EPI2ME labs wf-metagenomics

### ISSUE THREAD

**Issue by Drmegs** [epi2me-labs/labslauncher#37]
Everytime I run the wf-metagenomics tutorial this is the error I get. I have run the analysis with the demo data and it works  but wont work with my data

[ry](https://github.com/epi2me-labs/labslauncher/issues/new#)
[Resources](https://github.com/epi2me-labs/labslauncher/issues/new#resources)
[Tasks](https://github.com/epi2me-labs/labslauncher/issues/new#tasks)
[admiring_lovelace]
Nextflow workflow report
[admiring_lovelace]
Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 2.

The full error message was:

Error executing process > 'kraken_pipeline:progressive_bracken (1)'

Caused by:
  Process `kraken_pipeline:progressive_bracken (1)` terminated with an error exit status (2)

Command executed:

  # run bracken on the latest kreports, is this writing some outputs
  # alongside the inputs? seems at least {}.kreport_bracken_species.txt
  # is written alongside the input
  run_bracken.py \
      "database_dir" \
      "kraken.1.unclassified/unclassified.kreport.txt" \
      "1000" \
      "S" \
      "unclassified.bracken_report.txt"
  
  # do some stuff...
  awk -F '	' -v OFS='	' '{ print $2,$6 }' "unclassified.bracken_report.txt" \
      | awk -F '	' -v OFS='	' 'NR!=1 {print}' \
      | tee taxacounts.txt \
      | awk -F '	' -v OFS='	' '{ print $1 }' > taxa.txt
  taxonkit lineage         -j 2 \
      --data-dir taxonomy_dir \
      -R taxa.txt  > lineages.txt
  aggregate_lineages_bracken.py \
      -i "lineages.txt" -b "taxacounts.txt" \
      -u "kraken.1.unclassified/unclassified.kreport.txt" \
      -p "unclassified.kraken2"
  
  file1=`cat *.json`
  echo "{"'"unclassified"'": "$file1"}" >> "bracken.json"
  
  # collate the latest bracken outputs into state
  if [[ "1" != "1" ]]; then
      cp -r "NOSTATE" "bracken.1"
  else
      # make fresh directory
      mkdir "bracken.1"
  fi;
  
  # first output here is just for end user
  mv "kraken.1.unclassified/unclassified.kreport_bracken_species.txt" "bracken.1" || echo "No bracken report"
  mv "bracken.json" "bracken.1/unclassified.json"

Command exit status:
  2

Command output:
  b' >> Checking for Valid Options...\n ERROR: database_dir/database1000mers.kmer_distrib does not exist\n        Run bracken-build to generate the kmer distribution file.\n'

Command error:
  b''awk: cannot open unclassified.bracken_report.txt (No such file or directory)

Work dir:
  /mnt/c/Users/meaga/epi2melabs/instances/wf-metagenomics_f7c179f2-5dae-473d-983d-6ea1c524321c/work/ca/688912bc1e50127ca1e628c3c3fa0b

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by cjw85** [comment]
Could you please open and issue on the [wf-metagenomics](GitHub.com/epi2me-labs/wf-metagenomics) page.
