### ISSUE TITLE
Unable to install Epi2Me on Ubuntu

### ISSUE THREAD

**Issue by cantaylancapraz** [epi2me-labs/labslauncher#6]
Hi,

I'm trying to install epi2me lab to ubuntu, and I faced with following error. Do you have any solution for this?

```
Providing permissions to host user for notebook group...
Adding UID 0 to notebook group as nbhost
useradd: UID 0 is not unique
Executing command as: nbhost (0)
sudo: unknown user: nbhost
sudo: unable to initialize policy plugin
```

I installed epi2me application by downlading https://github.com/epi2me-labs/labslauncher/releases/download/v1.0.6/ont-epi2melabs-launcher-1.0.6-0.bionic.deb
Not: ubuntu image ubuntu-1804-bionic-v20210129

**Comment by cjw85** [comment]
Hi @cantaylancapraz,

This looks like you are trying to run Epi2melabs as the root user (UID 0). This is not advised (and from your error message not in fact possible). I suggest starting the launcher application with a standard user.

**Comment by cantaylancapraz** [comment]
Thanks, installing it with a standart user solved problem
