### ISSUE TITLE
Launcher ignores docker restrict option

### ISSUE THREAD

**Issue by cantaylancapraz** [epi2me-labs/labslauncher#7]
Hi,

On the settings part, there is "docker_restrict" option, and when I uncheck this option, program displays a message tell me to restart Launcher. When I restart, this option is updated as checked again. 

Do you have any recommendation?

Thanks

 docker_restrict option:
<img width="603" alt="Screen Shot 2021-01-31 at 01 37 32" src="https://user-images.githubusercontent.com/77298084/106369807-84746780-6365-11eb-8e28-8bc455d49268.png">

**Comment by cjw85** [comment]
Hi @cantaylancapraz,

I cannot reproduce this behaviour. Can you try deleting any files such as:

    ~/.config/EPI2ME Labs/Launcher.conf

and running the program again.

**Comment by cjw85** [comment]
@cantaylancapraz 

Did the above work for you?

**Comment by cantaylancapraz** [comment]
Actually, I tried. But I'm not sure if it solved problem. 

I removed Launcher.conf file, and launcher created this file again. 
```
aux_port=8889
container_cmd="start-notebook.sh  --NotebookApp.port_retries=0 --no-browser --notebook-dir=/"
data_bind=/epi2melabs/
data_mount=/home/taylancapraz
docker_args=
docker_restrict=false
download_link=https://labs.epi2me.io/downloads/
fixed_tag=
ftp_proxy=
github_repo=labslauncher
github_token=
github_user=epi2me-labs
help_link=https://labs.epi2me.io/quickstart/
http_proxy=
https_proxy=
image_name=ontresearch/epi2melabs-notebook
port=8888
registry=docker.io
send_pings=true
server_name=Epi2Me-Labs-Server
token=EPI2MELabs
version=1.0.6
```

Even though docker_restrict parameter is set as false in created Launcher.conf, application shows this option as ticked. Screenshot is as below. Maybe, this is just a representation issue. 

<img width="843" alt="Screen Shot 2021-02-04 at 00 41 37" src="https://user-images.githubusercontent.com/77298084/106813249-ca8d3c00-6681-11eb-9abd-100313546680.png">

**Comment by cjw85** [comment]
Thanks for the additional information. I have located the source of the issue. We will fix this ASAP.

Just to make sure you are aware of the implications of this setting. Disabling the restriction will potentially allow anyone with the `Token` setting from the start page to access the notebooks from any location. These people will be able to run arbitrary code on the computer running EPI2ME Labs.

As an alternative providing more security, you may wish to leave `docker_restrict` enabled and instead create an ssh tunnel from your Mac to you Ubuntu computer running EPI2MELabs, for example:

    ssh -Y -L 8888:localhost:8888 -L 8889:localhost:8889 <ubuntu_hostname>

**Comment by cantaylancapraz** [comment]
Thank you very much for your suggestions regarding security.

I'm doing port forwarding with ssh, but we wanted to make access a bit easier. As workaround, I installed ngnix reverse proxy on the local machine where the application is running, and expose port 8888. This workaround works perfectly, but as you suggested, additional security controls would be beneficial. 

Thanks

**Comment by cjw85** [comment]
v1.0.7 of the application is now available on the download page: https://labs.epi2me.io/downloads/

This should fix the issue. We're in the process of creating a command line interface to the application which might be of interest to you if you are regularly starting notebook servers on remote computers.

**Comment by cantaylancapraz** [comment]
Thanks, 

I upgraded version, and everything works correctly. 
And ngnix reverse proxy is not needed anymore. 

Thank you very much for your quick fix @cjw85.

**Comment by cantaylancapraz** [comment]
In addition, cli would make launch process much easier. Thank you in advance for this feature. We will definitely use it when complete. @cjw85

**Comment by cjw85** [comment]
@cantaylancapraz v1.0.8 of the launcher is now available from the downloads page: https://labs.epi2me.io/downloads/

On Ubuntu this includes the `labsmanager` program which can be used to start/stop/restart the server from a prompt without starting a graphical interface. Hopefully it should be fairly self-explanatory. Unlike the GUI it will not used saved settings (such as mount point and ports); each time `labsmanager` is run default settings are applied unless changed on the command line.

**Comment by cantaylancapraz** [comment]
@cjw85 thank you, I'll upgrade it as soon as possible. I'm sure that it will be very useful.
