### ISSUE TITLE
labsmanager on compute cluster

### ISSUE THREAD

**Issue by smallwerke** [epi2me-labs/labslauncher#8]
I have installed labslauncher onto a university compute cluster from source running "PYTHON=python3 make run". I removed the default launch of labslauncher from the makefile and everything completed successfully (initially it kept producing an error message since there is no X server running on the cluster and I thought the make process was failing)...

running labsmanager --start now produces the following error:
`Traceback (most recent call last):
  File "venv/bin/labsmanager", line 11, in <module>
    load_entry_point('labslauncher', 'console_scripts', 'labsmanager')()
  File "/home/asmussennc/EPI2ME/labslauncher/labslauncher/app.py", line 1063, in manager_main
    launcher_main(manager=True)
  File "/home/asmussennc/EPI2ME/labslauncher/labslauncher/app.py", line 1110, in launcher_main
    launcher = LabsLauncherCLI(settings, app)
  File "/home/asmussennc/EPI2ME/labslauncher/labslauncher/app.py", line 649, in __init__
    cur = self.docker.latest_available_tag
  File "/home/asmussennc/EPI2ME/labslauncher/labslauncher/dockerutil.py", line 265, in latest_available_tag
    self.image_name, client=self.docker, proxies=self.proxies)
  File "/home/asmussennc/EPI2ME/labslauncher/labslauncher/dockerutil.py", line 225, in docker
    raise ConnectionError("Could not communicate with docker.")
ConnectionError: Could not communicate with docker.
QWidget: Cannot create a QWidget without QApplication
Aborted
`
docker isn't installed on this cluster and I don't have the ability as a user to install it. Is it possible to run the program without using docker? 

thanks!

**Comment by cjw85** [comment]
Hi @smallwerke,

No, it is not possible to use EPI2MELabs without docker. The Launcher application is really just a convenient interface for starting and stopping a JupyterLab instance isolated inside a docker container. If you are interested in using the notebooks bundled within the environment they are available here:

https://github.com/epi2me-labs/tutorials/tree/master/tutorials

You will of course then have to install any of the software required for the notebooks in which you are interested in your own notebook environment.

**Comment by smallwerke** [comment]
thanks, I contacted the system admin and they said to ask you about running the docker image under Singularity? Would that be an acceptable solution?

**Comment by cjw85** [comment]
Singularity is something that we are increasingly thinking about, more in the context of some forthcomingnextflow workflows. We haven't thought of it for EPI2MELabs. It would certainly be possible, but perhaps not something we have time to implement right away.

All of the EPI2MELabs resources are available open source, including the container image definitions (https://github.com/epi2me-labs/nanolabs and https://github.com/epi2me-labs/tutorials).

**Comment by smallwerke** [comment]
well we're going to try running docker within singularity and make the EPI2MELabs from source to see if that works, I'll pass on how it goes...
